"""Orchestrate shipping a Sentry fix: fresh branch -> commit -> push -> open PR.

Runs only after the Pi coding agent has left a successful fix in the workspace
working tree. Sequences the safe git primitives in :mod:`git_ops` and the PR call
in :mod:`pr`, and enforces the "never touch the base branch" guarantee: the fix
always lands on a namespaced ``opensre/sentry-fix-*`` branch, the base branch is
never committed to or pushed, and the PR is opened *into* the base branch.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass

from integrations.github.client import resolve_github_token
from integrations.pi import PiCodingResult
from tools.cross_vendor.fix_sentry_issue.errors import ERR_NO_CHANGES, FixIssueError
from tools.cross_vendor.fix_sentry_issue.git_ops import (
    changed_paths,
    commit_paths,
    create_branch,
    default_branch,
    ensure_git_repo,
    file_fingerprints,
    push_branch,
    short_head,
)
from tools.cross_vendor.fix_sentry_issue.pr import PullRequest, open_pull_request

_BRANCH_PREFIX = "opensre/sentry-fix"
_SUBJECT_MAX = 72


@dataclass(frozen=True)
class ShipResult:
    """Outcome of shipping a fix as a pull request."""

    branch_name: str
    pr: PullRequest


def _slug(issue_id: str) -> str:
    """Filesystem/ref-safe slug for the issue id (falls back to 'issue')."""
    cleaned = re.sub(r"[^A-Za-z0-9_-]+", "-", issue_id).strip("-")
    return cleaned or "issue"


def build_branch_name(workspace: str, issue_id: str) -> str:
    """Namespaced, unique-ish branch name for this fix (never the base branch)."""
    suffix = short_head(workspace) or "wip"
    return f"{_BRANCH_PREFIX}-{_slug(issue_id)}-{suffix}"


def _commit_message(issue_id: str, sentry_url: str, summary: str) -> str:
    subject_body = summary.strip().splitlines()[0] if summary.strip() else "apply proposed fix"
    subject = f"fix: resolve Sentry issue {issue_id} — {subject_body}"[:_SUBJECT_MAX]
    lines = [subject, ""]
    if summary.strip():
        lines += [summary.strip(), ""]
    lines.append(f"Generated by OpenSRE (fix_sentry_issue) from {sentry_url}.")
    return "\n".join(lines)


def _pr_body(issue_id: str, sentry_url: str, result: PiCodingResult, changed: Sequence[str]) -> str:
    lines = [
        f"Automated fix proposed by OpenSRE for Sentry issue [{issue_id}]({sentry_url}).",
        "",
        "**Summary**",
        result.summary.strip() or "_(no summary provided)_",
    ]
    if changed:
        lines += ["", "**Files changed**"]
        lines += [f"- `{path}`" for path in changed]
    footer = (
        "> Generated by the OpenSRE `fix_sentry_issue` tool (pi.dev coding agent). "
        "Review before merging."
    )
    lines += ["", footer]
    return "\n".join(lines)


def ship_fix(
    workspace: str,
    *,
    issue_id: str,
    sentry_url: str,
    result: PiCodingResult,
    github_token: str | None = None,
    baseline: Mapping[str, str] | None = None,
) -> ShipResult:
    """Branch, commit, push, and open a PR for the fix in *workspace*.

    Assumes the Pi run already succeeded and left changes in the working tree.
    *baseline* is a ``{path: content-hash}`` fingerprint of files already dirty
    **before** the Pi run (see the tool's pre-run snapshot). A dirty file is
    committed only if it is new or its content changed since the baseline — so Pi's
    edits are always shipped (even to a file that was already dirty), while
    pre-existing WIP that Pi left untouched is excluded. Raises
    :class:`FixIssueError` (with a stable ``kind``) on any failure.
    """
    ensure_git_repo(workspace)

    # ``result.changed_files`` and a plain worktree scan both report the whole tree
    # vs HEAD, so neither isolates Pi's edits from pre-existing WIP. Compare content
    # hashes against the pre-run baseline: keep files Pi created or actually modified.
    pre_existing = dict(baseline or {})
    current = changed_paths(workspace)
    current_fingerprints = file_fingerprints(workspace, current)
    changed = [
        path
        for path in current
        if path not in pre_existing or current_fingerprints.get(path, "") != pre_existing[path]
    ]
    if not changed:
        raise FixIssueError(
            ERR_NO_CHANGES,
            "The Pi run left no new changes to commit (only pre-existing work-in-progress); "
            "nothing to open a PR for.",
        )

    # One credential for both the push and the PR call, so the push doesn't fall
    # back to a stale cached git credential (the usual cause of a 403 on push).
    token = resolve_github_token(github_token)

    base = default_branch(workspace)
    branch = build_branch_name(workspace, issue_id)

    create_branch(workspace, branch, base_default=base)

    # From here the workspace is on ``branch``. Any failure (commit, push, or PR)
    # leaves the user's changes on that branch, so tag it onto the error for the
    # caller to surface for manual recovery instead of reporting an empty branch.
    try:
        commit_paths(workspace, changed, _commit_message(issue_id, sentry_url, result.summary))
        push_branch(workspace, branch, base_default=base, github_token=token or None)
        pr = open_pull_request(
            workspace,
            head_branch=branch,
            base_branch=base,
            title=f"fix: resolve Sentry issue {issue_id}",
            body=_pr_body(issue_id, sentry_url, result, changed),
            github_token=token or None,
        )
    except FixIssueError as exc:
        exc.branch_name = branch
        raise
    return ShipResult(branch_name=branch, pr=pr)
